"""fix candidate unique constraint

Revision ID: 88ddc1555224
Revises: c9161fdd2031
Create Date: 2025-12-09 13:41:05.434760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88ddc1555224'
down_revision: Union[str, Sequence[str], None] = 'c9161fdd2031'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('candidates_user_id_key'), type_='unique')
        batch_op.create_unique_constraint('unique_candidate_per_position_election', ['user_id', 'position_id', 'election_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.drop_constraint('unique_candidate_per_position_election', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('candidates_user_id_key'), ['user_id'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
