"""add secure voting

Revision ID: 88ef675becd8
Revises: 621ea8f3ac68
Create Date: 2025-12-09 09:41:35.296687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '88ef675becd8'
down_revision: Union[str, Sequence[str], None] = '621ea8f3ac68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('previous_hash', sa.String(length=64), nullable=True),
    sa.Column('current_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_current_hash'), 'audit_logs', ['current_hash'], unique=True)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_table('election_tallies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('election_id', sa.Integer(), nullable=False),
    sa.Column('tallied_by', sa.Integer(), nullable=False),
    sa.Column('tallied_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('results_summary', sa.Text(), nullable=True),
    sa.Column('total_votes_decrypted', sa.Integer(), nullable=True),
    sa.Column('total_votes_verified', sa.Integer(), nullable=True),
    sa.Column('integrity_check_passed', sa.Boolean(), nullable=True),
    sa.Column('audit_hash', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['election_id'], ['elections.id'], ),
    sa.ForeignKeyConstraint(['tallied_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('audit_hash')
    )
    op.create_index(op.f('ix_election_tallies_id'), 'election_tallies', ['id'], unique=False)
    op.create_table('user_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_activity', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_sessions_id'), 'user_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_user_sessions_jti'), 'user_sessions', ['jti'], unique=True)
    op.create_table('encrypted_votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('anonymous_voter_id', sa.String(length=64), nullable=False),
    sa.Column('election_id', sa.Integer(), nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('encrypted_vote_data', sa.Text(), nullable=False),
    sa.Column('vote_hash', sa.String(length=64), nullable=False),
    sa.Column('vote_receipt', sa.String(length=20), nullable=False),
    sa.Column('receipt_hash', sa.String(length=64), nullable=False),
    sa.Column('commitment_hash', sa.String(length=64), nullable=False),
    sa.Column('cast_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('tallied', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['election_id'], ['elections.id'], ),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('receipt_hash')
    )
    op.create_index(op.f('ix_encrypted_votes_anonymous_voter_id'), 'encrypted_votes', ['anonymous_voter_id'], unique=False)
    op.create_index(op.f('ix_encrypted_votes_id'), 'encrypted_votes', ['id'], unique=False)
    op.create_index(op.f('ix_encrypted_votes_vote_hash'), 'encrypted_votes', ['vote_hash'], unique=True)
    op.create_index(op.f('ix_encrypted_votes_vote_receipt'), 'encrypted_votes', ['vote_receipt'], unique=True)
    op.create_table('vote_commitments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vote_hash', sa.String(length=64), nullable=False),
    sa.Column('commitment_factor', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['vote_hash'], ['encrypted_votes.vote_hash'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vote_hash')
    )
    op.create_index(op.f('ix_vote_commitments_id'), 'vote_commitments', ['id'], unique=False)
    op.create_table('vote_verifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vote_receipt', sa.String(length=20), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('verification_successful', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['vote_receipt'], ['encrypted_votes.vote_receipt'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vote_verifications_id'), 'vote_verifications', ['id'], unique=False)
    op.drop_index(op.f('ix_manifestos_id'), table_name='manifestos')
    op.drop_table('manifestos')
    op.add_column('candidates', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('candidates', sa.Column('manifestos', sa.JSON(), nullable=True))
    op.create_unique_constraint(None, 'candidates', ['user_id'])
    op.drop_constraint(op.f('candidates_position_id_fkey'), 'candidates', type_='foreignkey')
    op.drop_constraint(op.f('candidates_party_id_fkey'), 'candidates', type_='foreignkey')
    op.create_foreign_key(None, 'candidates', 'positions', ['position_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'candidates', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'candidates', 'political_parties', ['party_id'], ['id'], ondelete='SET NULL')
    op.drop_column('candidates', 'name')
    op.drop_column('candidates', 'profile_image_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('profile_image_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('candidates', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'candidates', type_='foreignkey')
    op.drop_constraint(None, 'candidates', type_='foreignkey')
    op.drop_constraint(None, 'candidates', type_='foreignkey')
    op.create_foreign_key(op.f('candidates_party_id_fkey'), 'candidates', 'political_parties', ['party_id'], ['id'])
    op.create_foreign_key(op.f('candidates_position_id_fkey'), 'candidates', 'positions', ['position_id'], ['id'])
    op.drop_constraint(None, 'candidates', type_='unique')
    op.drop_column('candidates', 'manifestos')
    op.drop_column('candidates', 'user_id')
    op.create_table('manifestos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('candidate_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('priority', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], name=op.f('manifestos_candidate_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('manifestos_pkey'))
    )
    op.create_index(op.f('ix_manifestos_id'), 'manifestos', ['id'], unique=False)
    op.drop_index(op.f('ix_vote_verifications_id'), table_name='vote_verifications')
    op.drop_table('vote_verifications')
    op.drop_index(op.f('ix_vote_commitments_id'), table_name='vote_commitments')
    op.drop_table('vote_commitments')
    op.drop_index(op.f('ix_encrypted_votes_vote_receipt'), table_name='encrypted_votes')
    op.drop_index(op.f('ix_encrypted_votes_vote_hash'), table_name='encrypted_votes')
    op.drop_index(op.f('ix_encrypted_votes_id'), table_name='encrypted_votes')
    op.drop_index(op.f('ix_encrypted_votes_anonymous_voter_id'), table_name='encrypted_votes')
    op.drop_table('encrypted_votes')
    op.drop_index(op.f('ix_user_sessions_jti'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_id'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index(op.f('ix_election_tallies_id'), table_name='election_tallies')
    op.drop_table('election_tallies')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_current_hash'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
