"""Add election_id to candidates

Revision ID: c9161fdd2031
Revises: 3c2c87361e6e
Create Date: 2025-12-09 12:23:12.866004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9161fdd2031'
down_revision: Union[str, Sequence[str], None] = '3c2c87361e6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('election_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'elections', ['election_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('election_id')

    # ### end Alembic commands ###
